name: Purge Cloudflare cache

on:
  deployment_status:

jobs:
  purge:
    name: Purge Cloudflare cache
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'github-pages'
    steps:
      - name: Purge Cloudflare cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything": true}' \
            --fail-with-body
